### PR TITLE
Design & SQL

### PR DESCRIPTION
**Pull request by ffivarra**
Adds the list/view pages. Design is integrated with the "client protosite." Just need to figure out how to correctly display the news feed URLs using SQL.

### CODE REVIEW

**Comment by Tedwinder** [comment]
Frankie, is there code to add a "News" tab to the Nav of the protosite? If
so, which file is that in?

**Comment by ffivarra** [comment]
Yes, it's in the "config_inc.php" file inside the "inc_0700" folder, beginning around line 89. Sorry, I didn't think to include that code here. I just added this line: `$nav1['n_index.php'] = "News~Get all your news in one place!";`

**Comment by souhaAmor** [comment]
Francisco which file is for categories list ,
                                        feeds list
                              and    RSS URL

**Comment by Tedwinder** [comment]
Oh cool- thanks!

**Comment by ffivarra** [comment]
Souha, I'm a bit confused as to what you're asking. `CategoryID`, `CategoryName` and `CategoryDescription` are all referenced in the "n_index.php" file, and `FeedName` and `FeedDescription` are referenced in the "news_view.php" file. As I mentioned in my first comment, I can't quite figure out how to have the RSS URLs display correctly, but I imagine that code would go in the "news_view.php" file.

**Comment by Tedwinder** [comment]
I agree it will go in the news view- I'm re-writing the files as
object-oriented classes and will get a draft posted in a bit. . . The OOP
rewrite may change the organization a bit FYI.

**Comment by Tedwinder** [comment]
Also FYI I don't believe we need the news_list file, which is essentially a
duplicate of news_view.

**Comment by Tedwinder** [comment]
Souha, if I'm not mistaken, we need to place the feed URL into the feed
table, rather than store actual descriptions there, so each CategoryID
should link up with 3 different URLs on the second table. . . . That's how
I read the assignment.

For example,
Category: Business
Feed1Name: Google Business
Feed1Description: Google News Service with up-to-date news on hot current
topics
Feed1URL: http://. . . .

**Comment by souhaAmor** [comment]
Do you mean we need to store URLs in the feed table ? if this what you mean
, that's what I did .

Actually I did that part of coding , sql queries and few changes in the
code to work perfectly. I just couldn't understant your files that's why I
don't know where to put my code.

check what I did , I think this is how it should look like

http://souhaamor.com/wn16/surveys/list2.php

**Comment by Tedwinder** [comment]
Did you look at my view page?

**Comment by Tedwinder** [comment]
Can we maybe talk on the phone?  I think it would be better to avoid
duplication of work and misunderstandings. . . . my number is 206-349-1013.
best way (if you have iphone) is to call FaceTime audio, because the signal
is weak where I live - or viber or such. . .

**Pull request merged**
